from src.backend.models.slide_template import SlideTemplate
from src.protocols.slide_generation_protocol import SlideGenerationProtocol


class MockSlideGenerator(SlideGenerationProtocol):
    """
    Mock implementation of the slide generation protocol for testing.
    """

    def invoke_slide_gen_chain(
        self, script_content: str, template: SlideTemplate
    ) -> str:
        """
        Returns a fixed markdown string for testing purposes.
        """
        return f"""---
marp: true
theme: {template.id}
---

# Mock Generated Slide

This slide was generated by the `MockSlideGenerator`.

- **Script Content Length:** {len(script_content)}
- **Template Name:** {template.name}

"""
