DEBUG = true
USE_LOCAL_CLIENT = false

OLM_API_ENDPOINT = "http://localhost:11434"
OLLAMA_MODEL = "qwen3:0.6b"

# --- Analysis Configuration ---
ARGUMENT_FLOW_DIVISOR = 4           # Divisor for argument flow summary length

# --- Prompt Configuration ---
MAX_PROMPT_LENGTH = 8000            # Maximum prompt length to prevent context overflow

# --- Timeout Configuration (in seconds) ---
LLM_TIMEOUT = 600              # LLM request timeout
CHAIN_TIMEOUT = 2400            # Complete chain execution timeout
MARP_TIMEOUT = 120             # Marp file generation timeout 
PDF_CONVERSION_TIMEOUT = 60    # PDF to image conversion timeout 

# --- Streamlit Configuration ---
HOST_IP = "127.0.0.1"
TEST_PORT = "8502"
DEV_PORT = "8503"


