DEBUG = true
USE_LOCAL_CLIENT = true
OLM_API_ENDPOINT = "http://localhost:11434"
OLLAMA_MODEL = "qwen3:0.6b"

# --- Streamlit Configuration ---
HOST_IP = "127.0.0.1"
TEST_PORT = "8502"
DEV_PORT = "8503"

