DEBUG = true
USE_LOCAL_CLIENT = false

OLM_API_ENDPOINT = "http://localhost:11434"
OLLAMA_MODEL = "qwen3:0.6b"

# --- Timeout Configuration (in seconds) ---
LLM_TIMEOUT = 300              # LLM request timeout (5 minutes)
CHAIN_TIMEOUT = 600            # Complete chain execution timeout (10 minutes)
MARP_TIMEOUT = 120             # Marp file generation timeout (2 minutes)
PDF_CONVERSION_TIMEOUT = 60    # PDF to image conversion timeout (1 minute)

# --- Streamlit Configuration ---
HOST_IP = "127.0.0.1"
TEST_PORT = "8502"
DEV_PORT = "8503"

