# .streamlit/secrets.toml

# --- Debug Configuration ---
# Set to "true" to enable debug mode
DEBUG = "true"

# --- Streamlit Configuration ---
# These are typically used for local development and testing
HOST_IP = "127.0.0.1"
HOST_PORT = 8501
TEST_PORT = 8502
DEV_PORT = 8503
