# --- Debug Configuration ---
DEBUG = true

# --- LLM Configuration ---
USE_TWO_STAGE_LLM = true

# For production with real Ollama API (set DEBUG=false)
# OLM_API_ENDPOINT = "http://localhost:8000"
# OLLAMA_MODEL = "qwen3:0.6b"

# --- Streamlit Configuration ---
HOST_IP = "127.0.0.1"
TEST_PORT = "8502"
DEV_PORT = "8503"

